/**
 * PUBLISHING PIPELINE — standalone build.
 *
 * Drop this single file into src/trigger/ and deploy. Nothing to clone,
 * nothing to npm install: it uses only @trigger.dev/sdk and
 * @aws-sdk/client-s3, which this project already has, plus your own
 * utils/storageClient and utils/env.
 *
 * It registers two tasks:
 *
 *   publish-planner   hourly cron. Lists new renders in Tigris, routes them
 *                     through the safety rail, assigns staggered slots inside
 *                     your posting window, and queues one delayed job each.
 *
 *   publish-one       wakes at its slot, re-checks the rail, and publishes.
 *                     Bluesky and Telegram are live; the other lanes abort
 *                     with a clear message until their adapters exist.
 *
 * Environment variables it reads (Trigger.dev > Environment Variables, and
 * remember they are PER ENVIRONMENT):
 *
 *   TIGRIS_BUCKET_NAME
 *   BLUESKY_HANDLE, BLUESKY_APP_PASSWORD
 *   TELEGRAM_BOT_TOKEN, TELEGRAM_CHANNEL_CHAT_ID
 *
 * DO NOT EDIT THIS FILE. It is generated from src/ by
 * scripts/build-standalone.mjs, and it is the same code the 185-test suite
 * runs against. Edit the sources and rebuild, or the two will drift.
 */

import {
  ListObjectsV2Command,
  GetObjectCommand,
  CopyObjectCommand,
  HeadObjectCommand,
  DeleteObjectCommand,
} from "@aws-sdk/client-s3";
import { logger, schedules, task, AbortTaskRunError } from "@trigger.dev/sdk/v3";
import { requireEnv } from "../utils/env.js";
import { tigrisClient } from "../utils/storageClient.js";

// ==========================================================================
// src/utils/contentRouting.ts
// ==========================================================================

/**
 * Which asset is allowed to go where.
 *
 * This is the safety rail for the whole publishing pipeline, and it is the one
 * part of the system where a mistake cannot be undone. Explicit material
 * reaching Instagram, TikTok, YouTube, Facebook or Telegram does not get fixed by
 * deleting the post: the account is gone, and the audience with it. Every other
 * failure in this project is recoverable. This one is not.
 *
 * So the rule lives in code rather than in a naming convention someone has to
 * remember, and it is enforced TWICE — once when an asset is routed, and again
 * immediately before a publish call goes out. Two independent checks, because
 * the cost of the first one having a bug is permanent.
 *
 * Three principles, all of which this project has already learned the hard way:
 *
 *   1. FAIL CLOSED. An asset whose classification cannot be read goes NOWHERE.
 *      It never falls back to the social platforms. Same shape as the sweeper's
 *      dry-run flag: the dangerous direction requires an exact opt-in, so every
 *      typo lands on the safe side.
 *
 *   2. FAIL LOUDLY. "Goes nowhere" must never mean "silently skipped". An
 *      unroutable asset returns a stated reason so the caller can raise it. A
 *      job that logs a problem and returns normally is recorded as a success,
 *      and nobody ever finds out.
 *
 *   3. NO SUBSTRING MATCHING. Classification reads the FIRST PATH SEGMENT of the
 *      key and compares it exactly. "safe/explicit-pose/01.png" is safe — it is
 *      in the safe folder — and no amount of the word "explicit" appearing later
 *      in the key changes that.
 */

/** What an asset is, for routing purposes. Nothing else is a valid value. */
export type ContentClass = "safe" | "explicit";

/** What kind of media it is. Some platforms accept only one. */
export type MediaKind = "image" | "video";

export type PlatformId =
  | "bluesky"
  | "instagram"
  | "facebook"
  | "telegram"
  | "tiktok"
  | "youtube"
  | "fanvue";

export interface Platform {
  id: PlatformId;
  label: string;
  /** Content classes this destination may receive. */
  accepts: readonly ContentClass[];
  /** Media kinds this destination can publish at all. */
  media: readonly MediaKind[];
  /**
   * The platform's own published ceiling per 24h, where one exists, as a hard
   * backstop independent of the configured cadence. Undefined means "no
   * documented hard cap" — which is NOT the same as unlimited, so the
   * configured cadence still applies.
   */
  apiCeilingPerDay?: number;
  /** True for anything that is not a mainstream social network. */
  adultPlatform: boolean;
}

/**
 * Object.freeze is SHALLOW. Freezing the outer table leaves every platform
 * object inside it writable, so `PLATFORMS.instagram.accepts = [...]` would
 * still succeed — and that single line is the whole catastrophe this file
 * exists to prevent. A safety rule that can be edited at runtime is not a
 * safety rule. This was caught by the freeze test, not by reading the code.
 */
function deepFreeze<T>(value: T): T {
  if (value === null || typeof value !== "object") return value;
  for (const key of Object.getOwnPropertyNames(value)) {
    deepFreeze((value as Record<string, unknown>)[key]);
  }
  return Object.freeze(value);
}

/**
 * Fansly is deliberately absent.
 *
 * It has no official developer API. Everything advertising itself as a "Fansly
 * API" is a third party that works by taking your Fansly session credentials —
 * for the account holding the earnings and payout details — and most are
 * scrapers besides. It stays a manual lane rather than an automated one.
 */
export const PLATFORMS: Readonly<Record<PlatformId, Platform>> = deepFreeze({
  bluesky: {
    id: "bluesky",
    label: "Bluesky",
    accepts: ["safe"],
    media: ["image", "video"],
    adultPlatform: false,
  },
  instagram: {
    id: "instagram",
    label: "Instagram",
    accepts: ["safe"],
    media: ["image", "video"],
    // Content Publishing API: 25 published posts per rolling 24 hours.
    apiCeilingPerDay: 25,
    adultPlatform: false,
  },
  facebook: {
    id: "facebook",
    label: "Facebook",
    accepts: ["safe"],
    media: ["image", "video"],
    adultPlatform: false,
  },
  telegram: {
    id: "telegram",
    label: "Telegram",
    accepts: ["safe"],
    media: ["image", "video"],
    // Bot API: 10 MB for a photo, 50 MB for other files, both via
    // multipart/form-data. Caption limit 1024 characters. Confirmed against the
    // Bot API docs, not assumed.
    adultPlatform: false,
  },
  tiktok: {
    id: "tiktok",
    label: "TikTok",
    accepts: ["safe"],
    // Confirmed against the Content Posting API: photo posts are supported via
    // media_type PHOTO, 1-10 images, JPG/JPEG. So this lane needs no
    // image-to-video step.
    media: ["image", "video"],
    adultPlatform: false,
  },
  youtube: {
    id: "youtube",
    label: "YouTube Shorts",
    accepts: ["safe"],
    // Video only. A still image cannot be published as a Short at all.
    media: ["video"],
    // ~1600 quota units per upload against a 10,000/day default.
    apiCeilingPerDay: 6,
    adultPlatform: false,
  },
  fanvue: {
    id: "fanvue",
    label: "Fanvue",
    accepts: ["safe", "explicit"],
    media: ["image", "video"],
    adultPlatform: true,
  },
} as Record<PlatformId, Platform>);

export const ALL_PLATFORMS: readonly PlatformId[] = Object.freeze(
  Object.keys(PLATFORMS) as PlatformId[],
);

/**
 * The six mainstream lanes — the ones where a wrong post is unrecoverable.
 *
 * Derived from the flag rather than hand-listed, so adding a platform above
 * cannot leave this list quietly stale. A hand-written list in this package has
 * already gone out of date once, in install.sh, and nobody noticed until the
 * file it omitted turned out not to exist in the target repo.
 */
export const SOCIAL_PLATFORMS: readonly PlatformId[] = Object.freeze(
  ALL_PLATFORMS.filter((id) => !PLATFORMS[id].adultPlatform),
);

/** Storage prefixes that carry the classification. Exact, lowercase, no aliases. */
export const CLASS_PREFIX: Readonly<Record<ContentClass, string>> = Object.freeze({
  safe: "safe/",
  explicit: "explicit/",
});

export interface AssetRef {
  /** Object key in the hot bucket, e.g. "safe/2026-09-16/render-01.png". */
  key: string;
  kind: MediaKind;
}

/**
 * Read the classification off an object key.
 *
 * Returns null — never a guess — when the first path segment is not exactly
 * "safe" or "explicit". Case matters: S3 keys are case-sensitive, and being
 * lenient here is only ever dangerous in one direction. Treating "Safe/" as
 * safe would route a mislabelled asset to six public platforms; refusing it
 * means nothing posts and somebody notices. The second outcome is recoverable
 * and the first is not, so this is strict.
 */
export function classifyFromKey(key: string): ContentClass | null {
  const normalised = key.replace(/^\/+/, "");
  const firstSegment = normalised.slice(0, normalised.indexOf("/") + 1);
  if (firstSegment === CLASS_PREFIX.safe) return "safe";
  if (firstSegment === CLASS_PREFIX.explicit) return "explicit";
  return null;
}

export interface RoutingDecision {
  /** Destinations this asset may be published to. Empty is a valid answer. */
  destinations: PlatformId[];
  contentClass: ContentClass | null;
  /**
   * Every destination that was considered and rejected, with the reason.
   * Present so a run can say WHY nothing was published rather than reporting
   * an empty list as though it were a normal result.
   */
  rejected: Array<{ platform: PlatformId; reason: string }>;
  /**
   * Set when the asset cannot be routed at all. The caller must treat this as
   * an error, not as "nothing to do".
   */
  blockedReason?: string;
}

/**
 * Decide where an asset is allowed to go.
 *
 * `requested` narrows the candidates; omitting it considers every platform.
 * Narrowing can only ever REMOVE destinations — a caller cannot ask for a
 * destination the rules forbid and get it.
 */
export function routeAsset(
  asset: AssetRef,
  requested: readonly PlatformId[] = ALL_PLATFORMS,
): RoutingDecision {
  const contentClass = classifyFromKey(asset.key);
  const rejected: RoutingDecision["rejected"] = [];

  if (contentClass === null) {
    return {
      destinations: [],
      contentClass: null,
      rejected: [],
      blockedReason:
        `Cannot classify "${asset.key}": its first path segment is neither ` +
        `"${CLASS_PREFIX.safe}" nor "${CLASS_PREFIX.explicit}". Nothing is published for an ` +
        `asset whose classification is unknown — this is deliberate, not a bug. ` +
        `Move it under the correct prefix and re-queue it.`,
    };
  }

  const destinations: PlatformId[] = [];
  for (const id of requested) {
    const platform = PLATFORMS[id];
    if (!platform) {
      rejected.push({ platform: id, reason: `unknown platform "${id}"` });
      continue;
    }
    if (!platform.accepts.includes(contentClass)) {
      rejected.push({
        platform: id,
        reason: `${platform.label} accepts ${platform.accepts.join("/")} content only, this asset is ${contentClass}`,
      });
      continue;
    }
    if (!platform.media.includes(asset.kind)) {
      rejected.push({
        platform: id,
        reason: `${platform.label} cannot publish ${asset.kind} (accepts ${platform.media.join("/")})`,
      });
      continue;
    }
    destinations.push(id);
  }

  return { destinations, contentClass, rejected };
}

/**
 * The second, independent check. Adapters call this immediately before the
 * publish request goes out.
 *
 * It duplicates work routeAsset already did, on purpose. A routing bug that
 * slipped an explicit asset into the Instagram queue is caught here instead of
 * on Instagram, and the cost of the duplication is a few microseconds against
 * a permanent ban.
 *
 * Throws rather than returning false: there is no sensible way for a caller to
 * ignore this, so it should not be possible to ignore it by forgetting an if.
 */
export function assertPublishAllowed(platformId: PlatformId, asset: AssetRef): void {
  const platform = PLATFORMS[platformId];
  if (!platform) {
    throw new Error(`Refusing to publish: unknown platform "${platformId}".`);
  }

  const contentClass = classifyFromKey(asset.key);
  if (contentClass === null) {
    throw new Error(
      `Refusing to publish "${asset.key}" to ${platform.label}: its classification cannot be ` +
        `read from the key. An unclassified asset is never published anywhere.`,
    );
  }

  if (!platform.accepts.includes(contentClass)) {
    throw new Error(
      `BLOCKED: refusing to publish ${contentClass} content to ${platform.label}. ` +
        `Key "${asset.key}". This would risk permanent loss of the account, so it is ` +
        `refused at the last possible moment regardless of what queued it.`,
    );
  }

  if (!platform.media.includes(asset.kind)) {
    throw new Error(
      `Refusing to publish ${asset.kind} to ${platform.label}, which accepts ` +
        `${platform.media.join("/")} only. Key "${asset.key}".`,
    );
  }
}

/** Per-platform posting cadence. The configured rate, not the platform's ceiling. */
export interface Cadence {
  maxPostsPerDay: number;
  maxVideosPerDay: number;
}

/**
 * The agreed cadence: up to 5 posts per platform per 24h.
 *
 * Chosen by the client to look like a person rather than a feed, and it stays
 * below every API ceiling. That is worth being explicit about, because it
 * changes what the rate limiter is FOR: it is not a throttle holding the
 * account back, it is a backstop against this code misbehaving — a retry storm,
 * a duplicated fan-out, a scheduling bug draining the queue at once.
 *
 * Videos are capped lower than stills, at 4, and the reason is YouTube's quota
 * rather than anything about pacing. An upload costs roughly 1600 of the 10,000
 * units a project gets per day. Five uploads is 8000, which leaves almost
 * nothing for the metadata calls and the retry of a failed upload — and when
 * the quota runs out it is gone until the daily reset, so the failure lands on
 * everything else that day too. Four is 6400 and leaves real headroom. Raise it
 * once a quota increase has actually been granted, not before.
 */
export const DEFAULT_CADENCE: Readonly<Cadence> = Object.freeze({
  maxPostsPerDay: 5,
  maxVideosPerDay: 4,
});

/**
 * The effective daily limit for a platform and media kind: the stricter of the
 * configured cadence and the platform's own documented ceiling.
 *
 * Taking the minimum rather than trusting either alone means raising the
 * cadence later can never accidentally exceed what the API will accept, and a
 * platform loosening its ceiling does not silently change the posting rhythm.
 */
export function dailyLimitFor(
  platformId: PlatformId,
  kind: MediaKind,
  cadence: Cadence = DEFAULT_CADENCE,
): number {
  const platform = PLATFORMS[platformId];
  if (!platform) throw new Error(`Unknown platform "${platformId}".`);
  if (!platform.media.includes(kind)) return 0;

  const configured = kind === "video" ? cadence.maxVideosPerDay : cadence.maxPostsPerDay;
  const ceiling = platform.apiCeilingPerDay;
  return ceiling === undefined ? configured : Math.min(configured, ceiling);
}

/**
 * A stable idempotency key for one publish attempt.
 *
 * Keyed on asset AND destination, not the asset alone. One asset now fans out
 * to several platforms, so an attempt that succeeded on Bluesky and failed on X
 * must be able to retry X without re-posting to Bluesky. Keying on the asset
 * alone gives you exactly one of those two bugs and no way to have neither.
 */
export function publishIdempotencyKey(asset: AssetRef, platformId: PlatformId): string {
  return `${platformId}:${asset.key}`;
}

// ==========================================================================
// src/utils/captionGenerator.ts
// ==========================================================================

/**
 * Captions, generated per platform.
 *
 * One render fans out to several destinations, and posting the identical
 * caption to all of them is a cross-posting fingerprint in its own right —
 * the same reason the scheduler staggers the timing. So each platform gets its
 * own text, generated once per (asset, platform) pair.
 *
 * Every platform's own limit is enforced HERE, after generation, because a
 * model asked for "under 300 characters" will cheerfully return 340. The limit
 * is not a suggestion to the model, it is a hard truncation afterwards —
 * checked on graphemes for Bluesky and code units for Telegram, because that
 * is what each API actually counts.
 *
 * NOTHING HERE CAN PUBLISH. It returns strings. That matters: the model output
 * never chooses a destination, never sees a credential, and cannot cause a
 * post. If the model returns nonsense the worst case is a bad caption, not a
 * bad post to the wrong place.
 */


export const OPENAI_API = "https://api.openai.com/v1/chat/completions";

/** Per-platform caption limits, and what each API actually counts. */
export interface CaptionLimit {
  max: number;
  /** Bluesky counts graphemes; Telegram counts UTF-16 code units. */
  unit: "grapheme" | "codeunit";
}

export const CAPTION_LIMITS: Readonly<Record<PlatformId, CaptionLimit>> = Object.freeze({
  bluesky: { max: 300, unit: "grapheme" },
  telegram: { max: 1024, unit: "codeunit" },
  instagram: { max: 2200, unit: "codeunit" },
  facebook: { max: 2000, unit: "codeunit" },
  tiktok: { max: 2200, unit: "codeunit" },
  youtube: { max: 100, unit: "codeunit" },
  fanvue: { max: 1000, unit: "codeunit" },
});

export function measure(text: string, unit: CaptionLimit["unit"]): number {
  if (unit === "codeunit") return text.length;
  if (typeof Intl !== "undefined" && "Segmenter" in Intl) {
    const segmenter = new Intl.Segmenter(undefined, { granularity: "grapheme" });
    let count = 0;
    for (const _ of segmenter.segment(text)) count += 1;
    return count;
  }
  return [...text].length;
}

/**
 * Cut to length without splitting a grapheme or leaving a half-word.
 *
 * Slicing a string at a character index can land inside an emoji and produce a
 * replacement glyph, which looks like a bug in your feed rather than a long
 * caption. Backing off to the last space is cosmetic but free.
 */
export function truncateTo(text: string, limit: CaptionLimit): string {
  if (measure(text, limit.unit) <= limit.max) return text;

  let units: string[];
  if (limit.unit === "grapheme" && typeof Intl !== "undefined" && "Segmenter" in Intl) {
    const segmenter = new Intl.Segmenter(undefined, { granularity: "grapheme" });
    units = [...segmenter.segment(text)].map((s) => s.segment);
  } else {
    units = limit.unit === "grapheme" ? [...text] : text.split("");
  }

  // Leave room for the ellipsis so the RESULT is within the limit, not the
  // text before it.
  const room = Math.max(0, limit.max - 1);
  let cut = units.slice(0, room).join("");
  const lastSpace = cut.lastIndexOf(" ");
  if (lastSpace > room * 0.6) cut = cut.slice(0, lastSpace);
  return `${cut.trimEnd()}…`;
}

export interface CaptionContext {
  asset: AssetRef;
  platform: PlatformId;
  /** The link-in-bio or funnel URL this should drive traffic to. */
  linkUrl?: string;
  /** Free-form notes about the render: mood, setting, whatever helps. */
  description?: string;
  /** How hard the call to action pushes. The client's call, not mine. */
  intensity?: "soft" | "direct" | "hard";
}

/**
 * Per-platform style rules.
 *
 * These are about what each platform's audience and format reward, not about
 * what is allowed — the routing rail already decided the post is permitted
 * before this is ever called.
 */
export function styleFor(platform: PlatformId): string {
  switch (platform) {
    case "bluesky":
      return "Conversational and dry. No hashtags — they do almost nothing here. Under 300 characters.";
    case "telegram":
      return "Direct, like a message to people who already subscribed. A single clear call to action.";
    case "instagram":
      return "Visual-first, a line or two, then 3-5 relevant hashtags on their own line.";
    case "facebook":
      return "Slightly longer and warmer. Minimal hashtags.";
    case "tiktok":
      return "Short, hooky, front-loaded. 2-4 trending-style hashtags.";
    case "youtube":
      return "A Shorts TITLE, not a caption. Under 100 characters, hooky, no hashtags.";
    case "fanvue":
      return "Speaking to paying subscribers who already bought. Warm, no hard sell.";
    default:
      return "Short and plain.";
  }
}

export function buildPrompt(context: CaptionContext): string {
  const intensity = context.intensity ?? "direct";
  const cta =
    intensity === "hard"
      ? "End with a strong, explicit instruction to click the link and subscribe."
      : intensity === "soft"
        ? "End with a light, low-pressure mention of the link."
        : "End with a clear call to action pointing at the link.";

  return [
    `Write a single caption for a post on ${PLATFORMS[context.platform]?.label ?? context.platform}.`,
    `Style: ${styleFor(context.platform)}`,
    context.description ? `About the image: ${context.description}` : "",
    context.linkUrl ? `Link to drive traffic to: ${context.linkUrl}` : "",
    cta,
    "Return ONLY the caption text. No quotes, no preamble, no explanation, no alternatives.",
  ]
    .filter(Boolean)
    .join("\n");
}

/**
 * Strip the things a chat model adds even when told not to.
 *
 * Asking for "only the caption" gets you the caption about nine times in ten.
 * The tenth comes wrapped in quotes, or prefixed with "Caption:", or as a
 * numbered list of three options. Cleaning that up is cheaper than a retry and
 * far cheaper than posting `"Caption: 1. ..."` to a public feed.
 */
export function cleanModelOutput(raw: string): string {
  let text = raw.trim();

  // A numbered or bulleted list: take the first item only.
  const listMatch = /^(?:\d+[.)]|[-*•])\s+(.+?)(?:\n|$)/s.exec(text);
  if (listMatch) text = listMatch[1]!.trim();

  text = text.replace(/^(?:caption|post|text)\s*[:\-—]\s*/i, "").trim();

  // Matching wrapping quotes, straight or curly.
  const quoted = /^(["'“”‘’])([\s\S]*)\1$/.exec(text);
  if (quoted) text = quoted[2]!.trim();
  if (/^"[\s\S]*"$/.test(text)) text = text.slice(1, -1).trim();
  if (/^“[\s\S]*”$/.test(text)) text = text.slice(1, -1).trim();

  return text.replace(/\n{3,}/g, "\n\n").trim();
}

export type Fetcher = typeof fetch;

export interface CaptionOptions {
  fetch?: Fetcher;
  apiKey?: string;
  model?: string;
  api?: string;
}

export function openaiKeyFromEnv(env: NodeJS.ProcessEnv = process.env): string {
  const key = (env.OPENAI_API_KEY ?? "").trim();
  if (key === "") {
    throw new Error(
      "Cannot generate captions: OPENAI_API_KEY is not set. Trigger.dev variables are " +
        "per-environment — set in Development is not set in Production.",
    );
  }
  return key;
}

/**
 * Generate one caption.
 *
 * Throws rather than returning a placeholder when the model fails. A silent
 * fallback to "New render" would publish for weeks before anyone noticed the
 * captions had stopped being written.
 */
export async function generateCaption(
  context: CaptionContext,
  options: CaptionOptions = {},
): Promise<string> {
  const fetcher = options.fetch ?? fetch;
  const apiKey = options.apiKey ?? openaiKeyFromEnv();
  const model = options.model ?? "gpt-4o-mini";
  const api = options.api ?? OPENAI_API;

  const response = await fetcher(api, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model,
      messages: [{ role: "user", content: buildPrompt(context) }],
      // Some variation is the point — identical captions across posts are a
      // spam signal on every one of these platforms.
      temperature: 0.9,
      max_tokens: 400,
    }),
  });

  if (!response.ok) {
    let detail = "";
    try {
      const body = (await response.json()) as { error?: { message?: string } };
      detail = body.error?.message ?? "";
    } catch {
      /* status alone will have to do */
    }
    // Never include the key, which is in the Authorization header.
    throw new Error(
      `Caption generation failed: HTTP ${response.status}${detail ? ` — ${detail}` : ""}`,
    );
  }

  const body = (await response.json()) as {
    choices?: Array<{ message?: { content?: string } }>;
  };
  const raw = body.choices?.[0]?.message?.content;
  if (!raw || raw.trim() === "") {
    throw new Error("Caption generation returned an empty response.");
  }

  const cleaned = cleanModelOutput(raw);
  if (cleaned === "") {
    throw new Error(`Caption generation returned nothing usable: ${JSON.stringify(raw.slice(0, 200))}`);
  }

  const limit = CAPTION_LIMITS[context.platform];
  return limit ? truncateTo(cleaned, limit) : cleaned;
}

/**
 * A deterministic caption, for when generation is not wanted or not available.
 *
 * Deliberately plain. It exists so the pipeline can be tested without spending
 * OpenAI calls, and so a caller can opt out of generation — NOT as a silent
 * fallback when generation fails. Failure throws; this has to be asked for.
 */
export function fallbackCaption(context: CaptionContext): string {
  const name = context.asset.key.split("/").pop() ?? "render";
  const base = context.description?.trim() || `New ${context.asset.kind}: ${name}`;
  const withLink = context.linkUrl ? `${base}\n${context.linkUrl}` : base;
  const limit = CAPTION_LIMITS[context.platform];
  return limit ? truncateTo(withLink, limit) : withLink;
}

// ==========================================================================
// src/utils/publishScheduler.ts
// ==========================================================================

/**
 * When each post actually goes out.
 *
 * At 3-5 posts a day the volume is never the risk — the timing is. Six
 * destinations receiving the identical asset in the same minute, every time, is
 * the clearest automation signal there is, and it is exactly the pattern spam
 * filters look for. So one render fans out to many destinations, but the slots
 * are spread across a posting window with jitter, and no two land together.
 *
 * Three properties this has to have, and each one is a test below:
 *
 *   DETERMINISTIC. The jitter is derived from the idempotency key, not from
 *   Math.random(). The same asset therefore always gets the same slot, so
 *   re-planning after a crash produces the identical schedule instead of a
 *   second, differently-timed set of posts. It also means the tests are not
 *   flaky, which is the only reason anyone would believe them.
 *
 *   INSIDE HUMAN HOURS. Three posts at 03:00 reads as a bot however modest the
 *   count. Slots fall inside a configured window, in the audience's timezone,
 *   never outside it.
 *
 *   SPACED. A minimum gap between consecutive posts to the same platform, so a
 *   burst cannot form even if a backlog drains at once.
 */


export interface PostingWindow {
  /** First hour a post may land, 0-23, in the configured timezone. */
  startHour: number;
  /** Last hour a post may START in, 0-23 inclusive. */
  endHour: number;
}

export interface ScheduleConfig {
  /**
   * IANA timezone the window is expressed in. US Eastern by default: it covers
   * both American coasts sensibly, since evening in New York is late afternoon
   * in Los Angeles.
   */
  timezone: string;
  window: PostingWindow;
  /** Minimum gap between two posts to the SAME platform. */
  minGapMinutes: number;
  /**
   * Minimum gap between the same asset landing on two DIFFERENT platforms.
   * This is the cross-posting fingerprint, so it matters more than it looks.
   */
  minCrossPlatformGapMinutes: number;
  cadence: Cadence;
}

export const DEFAULT_SCHEDULE: Readonly<ScheduleConfig> = Object.freeze({
  timezone: "America/New_York",
  window: Object.freeze({ startHour: 9, endHour: 21 }),
  minGapMinutes: 90,
  minCrossPlatformGapMinutes: 7,
  cadence: DEFAULT_CADENCE,
});

export interface ScheduledPost {
  asset: AssetRef;
  platform: PlatformId;
  /** When this should publish. */
  scheduledFor: Date;
  /** Stable across re-planning; the queue dedupes on it. */
  idempotencyKey: string;
}

export interface PlanInput {
  asset: AssetRef;
  destinations: readonly PlatformId[];
}

export interface PlanResult {
  scheduled: ScheduledPost[];
  /** Destinations dropped because the day is already full, with the reason. */
  deferred: Array<{ platform: PlatformId; asset: AssetRef; reason: string }>;
}

/**
 * A small deterministic hash. FNV-1a: not cryptographic, and it does not need
 * to be — it only has to spread keys evenly and give the same answer every run.
 */
export function hashKey(key: string): number {
  let hash = 0x811c9dc5;
  for (let i = 0; i < key.length; i += 1) {
    hash ^= key.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return hash >>> 0;
}

/** Deterministic value in [0, 1) derived from a key and a salt. */
export function deterministicUnit(key: string, salt: string): number {
  return hashKey(`${salt}:${key}`) / 0x100000000;
}

/**
 * The hour and minute a Date falls on in a given timezone.
 *
 * Done with Intl rather than by adding an offset, because a fixed offset is
 * wrong for half the year in any zone that observes daylight saving — and
 * "wrong for half the year" is the kind of bug that surfaces as posts drifting
 * an hour in March and nobody connecting it to the code.
 */
export function zonedParts(date: Date, timezone: string): { hour: number; minute: number } {
  const formatter = new Intl.DateTimeFormat("en-US", {
    timeZone: timezone,
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  });
  const parts = formatter.formatToParts(date);
  const hour = Number(parts.find((p) => p.type === "hour")?.value ?? "0");
  const minute = Number(parts.find((p) => p.type === "minute")?.value ?? "0");
  // Intl renders midnight as "24" in some environments.
  return { hour: hour === 24 ? 0 : hour, minute };
}

export function isInsideWindow(date: Date, config: ScheduleConfig): boolean {
  const { hour } = zonedParts(date, config.timezone);
  return hour >= config.window.startHour && hour <= config.window.endHour;
}

/**
 * Move a candidate time forward until it falls inside the posting window.
 *
 * Steps in whole hours and re-checks, rather than computing an offset, so it
 * stays correct across a daylight-saving boundary. Bounded at 48 iterations so
 * a misconfigured window (endHour before startHour, say) fails fast with a
 * clear error instead of looping forever.
 */
export function nextInsideWindow(from: Date, config: ScheduleConfig): Date {
  if (config.window.startHour > config.window.endHour) {
    throw new Error(
      `Posting window is inverted: startHour ${config.window.startHour} is after endHour ` +
        `${config.window.endHour}. A window that never opens would silently schedule nothing.`,
    );
  }
  let candidate = new Date(from.getTime());
  for (let i = 0; i < 48; i += 1) {
    if (isInsideWindow(candidate, config)) return candidate;
    // Advance to the top of the next hour.
    candidate = new Date(candidate.getTime() + 60 * 60 * 1000);
    candidate.setUTCSeconds(0, 0);
  }
  throw new Error(
    `Could not find a slot inside ${config.window.startHour}:00-${config.window.endHour}:59 ` +
      `${config.timezone} within 48 hours of ${from.toISOString()}.`,
  );
}

/**
 * Plan where a batch of assets lands.
 *
 * `alreadyScheduled` is what the queue already holds for the next 24 hours, so
 * the daily limits and the spacing account for posts planned by an earlier run.
 * Without it every invocation would think the day was empty and the limits
 * would mean nothing.
 */
export function planSchedule(
  inputs: readonly PlanInput[],
  now: Date,
  alreadyScheduled: readonly ScheduledPost[] = [],
  config: ScheduleConfig = DEFAULT_SCHEDULE,
): PlanResult {
  const scheduled: ScheduledPost[] = [];
  const deferred: PlanResult["deferred"] = [];

  // Per-platform view of the next 24h, seeded with what is already queued.
  const horizonMs = now.getTime() + 24 * 60 * 60 * 1000;
  const taken = new Map<PlatformId, Date[]>();
  for (const post of alreadyScheduled) {
    if (post.scheduledFor.getTime() > horizonMs) continue;
    const list = taken.get(post.platform) ?? [];
    list.push(post.scheduledFor);
    taken.set(post.platform, list);
  }

  const seen = new Set(alreadyScheduled.map((p) => p.idempotencyKey));

  for (const input of inputs) {
    // Cross-platform offset is per asset, so the same render does not hit
    // every destination at once. Order is deterministic but varies by asset,
    // so it is not always Bluesky first.
    const ordered = [...input.destinations].sort(
      (a, b) =>
        deterministicUnit(input.asset.key, a) - deterministicUnit(input.asset.key, b),
    );

    let crossOffsetMinutes = 0;
    for (const platform of ordered) {
      const idempotencyKey = publishIdempotencyKey(input.asset, platform);

      if (seen.has(idempotencyKey)) {
        deferred.push({
          platform,
          asset: input.asset,
          reason: `already scheduled — ${idempotencyKey} is in the queue, not duplicating it`,
        });
        continue;
      }

      const limit = dailyLimitFor(platform, input.asset.kind, config.cadence);
      const existing = taken.get(platform) ?? [];
      if (existing.length >= limit) {
        deferred.push({
          platform,
          asset: input.asset,
          reason:
            `${PLATFORMS[platform].label} already has ${existing.length} post(s) in the next 24h ` +
            `and the limit for ${input.asset.kind} is ${limit}. Deferred, not dropped — it will be ` +
            `picked up by the next planning pass.`,
        });
        continue;
      }

      // Start from the later of: now plus the cross-platform stagger, or the
      // last post to this platform plus the minimum gap.
      const lastForPlatform = existing.length
        ? Math.max(...existing.map((d) => d.getTime()))
        : 0;
      const earliest = Math.max(
        now.getTime() + crossOffsetMinutes * 60 * 1000,
        lastForPlatform ? lastForPlatform + config.minGapMinutes * 60 * 1000 : 0,
      );

      // Jitter derived from the key, never from a clock or a random source, so
      // the same asset always lands in the same slot.
      const jitterMinutes = Math.floor(
        deterministicUnit(idempotencyKey, "jitter") * config.minGapMinutes,
      );
      const candidate = new Date(earliest + jitterMinutes * 60 * 1000);
      const slot = nextInsideWindow(candidate, config);

      scheduled.push({ asset: input.asset, platform, scheduledFor: slot, idempotencyKey });
      seen.add(idempotencyKey);
      taken.set(platform, [...existing, slot]);

      crossOffsetMinutes += config.minCrossPlatformGapMinutes;
    }
  }

  scheduled.sort((a, b) => a.scheduledFor.getTime() - b.scheduledFor.getTime());
  return { scheduled, deferred };
}

/** Posts whose time has come. Everything else stays queued. */
export function duePosts(queue: readonly ScheduledPost[], now: Date): ScheduledPost[] {
  return queue
    .filter((post) => post.scheduledFor.getTime() <= now.getTime())
    .sort((a, b) => a.scheduledFor.getTime() - b.scheduledFor.getTime());
}

// ==========================================================================
// src/utils/blueskyClient.ts
// ==========================================================================

/**
 * Bluesky (AT Protocol) publishing.
 *
 * Bluesky goes first among the six lanes for one reason: it needs no app review,
 * so the entire pipeline — render, route, schedule, pace, publish — can be
 * proven end to end against a real platform while Instagram and TikTok are
 * still sitting in their approval queues.
 *
 * Wire format taken from the AT Protocol documentation rather than from memory,
 * because the last adapter written on this project against an assumed format
 * had 27 passing tests and still failed on the first real call. The three calls:
 *
 *   POST /xrpc/com.atproto.server.createSession   {identifier, password}
 *                                                  -> {accessJwt, refreshJwt, did}
 *   POST /xrpc/com.atproto.repo.uploadBlob        raw bytes, Content-Type: <mime>
 *                                                  -> {$type:"blob", ref:{$link}, mimeType, size}
 *   POST /xrpc/com.atproto.repo.createRecord      {repo, collection, record}
 *
 * The limits below are the protocol's, not guesses, and they are enforced
 * BEFORE the request goes out. Finding out that a render is too large by
 * uploading it and reading the error wastes the upload and produces a message
 * that does not name the file.
 */


export const BLUESKY_SERVICE = "https://bsky.social";

/**
 * A blob may not exceed 1,000,000 bytes. Note: one MILLION bytes, not one
 * mebibyte — 1048576 would be rejected. High-fidelity renders will exceed this
 * routinely, so the pipeline needs a downscaled derivative for this lane rather
 * than the master file.
 */
export const MAX_BLOB_BYTES = 1_000_000;

/** app.bsky.embed.images permits at most four. */
export const MAX_IMAGES_PER_POST = 4;

/** Post text limit, in graphemes. */
export const MAX_POST_GRAPHEMES = 300;

export const SUPPORTED_IMAGE_TYPES: readonly string[] = Object.freeze([
  "image/jpeg",
  "image/png",
  "image/webp",
]);

export interface BlueskyCredentials {
  /** Handle or DID, e.g. "ava.bsky.social". */
  identifier: string;
  /**
   * An APP PASSWORD, never the account password. App passwords are revocable
   * individually and cannot change the account's own password, so a leak is
   * contained and fixed by deleting one entry.
   */
  appPassword: string;
  service?: string;
}

export interface BlueskySession {
  accessJwt: string;
  refreshJwt: string;
  did: string;
  handle?: string;
}

export interface BlobRef {
  $type: "blob";
  ref: { $link: string };
  mimeType: string;
  size: number;
}

export interface ImageAttachment {
  bytes: Uint8Array;
  mimeType: string;
  /**
   * Alt text. Required by the lexicon — an empty string is permitted but a
   * real description is not optional politeness, it is what makes the post
   * readable to screen readers and it is a ranking signal besides.
   */
  alt: string;
}


export interface BlueskyOptions {
  fetch?: Fetcher;
  service?: string;
  now?: () => Date;
}

/**
 * Read credentials from the environment.
 *
 * Names match what the client set in the Trigger.dev variables panel. The
 * password never passes through chat, a repo or a log — this function is the
 * only place it is read, and nothing here ever prints it.
 */
export function blueskyCredentialsFromEnv(
  env: NodeJS.ProcessEnv = process.env,
): BlueskyCredentials {
  const identifier = (env.BLUESKY_HANDLE ?? "").trim();
  const appPassword = (env.BLUESKY_APP_PASSWORD ?? "").trim();

  const missing: string[] = [];
  if (identifier === "") missing.push("BLUESKY_HANDLE");
  if (appPassword === "") missing.push("BLUESKY_APP_PASSWORD");
  if (missing.length > 0) {
    throw new Error(
      `Cannot publish to Bluesky: missing environment variable(s): ${missing.join(", ")}. ` +
        `Trigger.dev variables are per-environment — set in Development is not set in Production.`,
    );
  }

  // An account password would work here, which is exactly why this check
  // exists: it would work, and nobody would notice until it leaked. App
  // passwords are formatted xxxx-xxxx-xxxx-xxxx.
  if (!/^[a-z0-9]{4}(-[a-z0-9]{4}){3}$/i.test(appPassword)) {
    throw new Error(
      `BLUESKY_APP_PASSWORD does not look like an app password (expected the form ` +
        `xxxx-xxxx-xxxx-xxxx). If you have put your real account password there, replace it: ` +
        `Settings > App Passwords. An app password is revocable on its own and cannot change ` +
        `the account password.`,
    );
  }

  return { identifier, appPassword, ...(env.BLUESKY_SERVICE ? { service: env.BLUESKY_SERVICE.trim() } : {}) };
}

async function xrpc(
  fetcher: Fetcher,
  service: string,
  method: string,
  init: RequestInit,
): Promise<Response> {
  return fetcher(`${service}/xrpc/${method}`, init);
}

/** Turn a non-2xx XRPC response into an error that names the method and reason. */
async function xrpcError(method: string, response: Response): Promise<Error> {
  let detail = "";
  try {
    const body = (await response.json()) as { error?: string; message?: string };
    detail = [body.error, body.message].filter(Boolean).join(": ");
  } catch {
    detail = (await response.text().catch(() => "")).slice(0, 300);
  }
  return new Error(
    `Bluesky ${method} failed: HTTP ${response.status}${detail ? ` — ${detail}` : ""}`,
  );
}

export async function createSession(
  credentials: BlueskyCredentials,
  options: BlueskyOptions = {},
): Promise<BlueskySession> {
  const fetcher = options.fetch ?? fetch;
  const service = options.service ?? credentials.service ?? BLUESKY_SERVICE;

  const response = await xrpc(fetcher, service, "com.atproto.server.createSession", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      identifier: credentials.identifier,
      password: credentials.appPassword,
    }),
  });

  if (!response.ok) throw await xrpcError("createSession", response);

  const session = (await response.json()) as BlueskySession;
  if (!session.accessJwt || !session.did) {
    throw new Error("Bluesky createSession returned no accessJwt or did.");
  }
  return session;
}

/**
 * Validate an image before it costs an upload.
 *
 * Returns the reasons rather than throwing so a caller can report all of them
 * at once; a caller that fixes one problem, re-runs, and discovers the next is
 * how a five-minute job becomes an afternoon.
 */
export function validateImage(image: ImageAttachment): string[] {
  const problems: string[] = [];
  if (!SUPPORTED_IMAGE_TYPES.includes(image.mimeType)) {
    problems.push(
      `mimeType "${image.mimeType}" is not supported by Bluesky (accepts ${SUPPORTED_IMAGE_TYPES.join(", ")})`,
    );
  }
  if (image.bytes.byteLength > MAX_BLOB_BYTES) {
    problems.push(
      `image is ${image.bytes.byteLength} bytes, over the ${MAX_BLOB_BYTES}-byte limit. ` +
        `Note that is one MILLION bytes, not one mebibyte. Publish a downscaled derivative ` +
        `to this lane rather than the master render.`,
    );
  }
  if (image.bytes.byteLength === 0) {
    problems.push("image is zero bytes");
  }
  if (typeof image.alt !== "string") {
    problems.push("alt text is required by the lexicon (an empty string is allowed)");
  }
  return problems;
}

/** Count graphemes, so an emoji is one character rather than two or four. */
export function graphemeLength(text: string): number {
  // Intl.Segmenter is in Node 18+. Falling back to [...text] would count an
  // emoji with a skin-tone modifier as several characters and reject a post
  // that Bluesky would have accepted.
  if (typeof Intl !== "undefined" && "Segmenter" in Intl) {
    const segmenter = new Intl.Segmenter(undefined, { granularity: "grapheme" });
    let count = 0;
    for (const _ of segmenter.segment(text)) count += 1;
    return count;
  }
  return [...text].length;
}

export function validatePostText(text: string): string[] {
  const length = graphemeLength(text);
  if (length > MAX_POST_GRAPHEMES) {
    return [`post text is ${length} graphemes, over the ${MAX_POST_GRAPHEMES} limit`];
  }
  return [];
}

export async function uploadBlob(
  session: BlueskySession,
  image: ImageAttachment,
  options: BlueskyOptions = {},
): Promise<BlobRef> {
  const fetcher = options.fetch ?? fetch;
  const service = options.service ?? BLUESKY_SERVICE;

  const problems = validateImage(image);
  if (problems.length > 0) {
    throw new Error(`Refusing to upload to Bluesky: ${problems.join("; ")}`);
  }

  const response = await xrpc(fetcher, service, "com.atproto.repo.uploadBlob", {
    method: "POST",
    headers: {
      "Content-Type": image.mimeType,
      Authorization: `Bearer ${session.accessJwt}`,
    },
    // A bare Uint8Array is not assignable to BodyInit under the current DOM lib
    // types (TS2322) — caught by typechecking in the client's own tsconfig
    // rather than here, which is the only reason it did not ship. A Blob is
    // unambiguous, and the explicit Content-Type header above still wins.
    // Buffer.from rather than the Uint8Array directly: a bare Uint8Array is
    // typed as Uint8Array<ArrayBufferLike>, which might be backed by a
    // SharedArrayBuffer and so is not assignable to BlobPart/BodyInit (TS2322).
    // Buffer is always ArrayBuffer-backed. Found by typechecking in the
    // client's own tsconfig, not here — twice in a row on this one line.
    body: new Blob([Buffer.from(image.bytes)], { type: image.mimeType }),
  });

  if (!response.ok) throw await xrpcError("uploadBlob", response);

  const body = (await response.json()) as { blob?: BlobRef };
  if (!body.blob?.ref?.$link) {
    throw new Error("Bluesky uploadBlob returned no blob reference.");
  }
  return body.blob;
}

export interface PostResult {
  uri: string;
  cid: string;
  /** Derived from the AT URI, so a human can open the post from a trace. */
  url: string;
}

export interface PostRequest {
  text: string;
  images?: ImageAttachment[];
  /** The asset this post is publishing, for the last-moment safety check. */
  asset?: AssetRef;
  /** ISO language codes, e.g. ["en"]. Improves reach and accessibility. */
  langs?: string[];
}

/**
 * Publish a post.
 *
 * Calls assertPublishAllowed first when an asset is supplied. That check has
 * already run at routing time; running it again here is deliberate duplication,
 * because it is the last point at which a routing bug can still be stopped, and
 * the thing it stops is unrecoverable.
 */
export async function publishPost(
  session: BlueskySession,
  request: PostRequest,
  options: BlueskyOptions = {},
): Promise<PostResult> {
  const fetcher = options.fetch ?? fetch;
  const service = options.service ?? BLUESKY_SERVICE;
  const now = options.now ?? (() => new Date());

  if (request.asset) {
    assertPublishAllowed("bluesky", request.asset);
  }

  const textProblems = validatePostText(request.text);
  if (textProblems.length > 0) {
    throw new Error(`Refusing to publish to Bluesky: ${textProblems.join("; ")}`);
  }

  const images = request.images ?? [];
  if (images.length > MAX_IMAGES_PER_POST) {
    throw new Error(
      `Refusing to publish to Bluesky: ${images.length} images, maximum is ${MAX_IMAGES_PER_POST}.`,
    );
  }

  const blobs: BlobRef[] = [];
  for (const image of images) {
    blobs.push(await uploadBlob(session, image, { ...options, service }));
  }

  const record: Record<string, unknown> = {
    $type: "app.bsky.feed.post",
    text: request.text,
    // Must be ISO 8601 with a Z suffix. toISOString() produces exactly that.
    createdAt: now().toISOString(),
    ...(request.langs ? { langs: request.langs } : {}),
  };

  if (blobs.length > 0) {
    record.embed = {
      $type: "app.bsky.embed.images",
      images: blobs.map((blob, index) => ({
        // alt is REQUIRED by the lexicon. An absent alt is a validation error
        // from the server, not a silently-omitted field.
        alt: images[index]!.alt ?? "",
        image: blob,
      })),
    };
  }

  const response = await xrpc(fetcher, service, "com.atproto.repo.createRecord", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${session.accessJwt}`,
    },
    body: JSON.stringify({
      repo: session.did,
      collection: "app.bsky.feed.post",
      record,
    }),
  });

  if (!response.ok) throw await xrpcError("createRecord", response);

  const body = (await response.json()) as { uri?: string; cid?: string };
  if (!body.uri || !body.cid) {
    throw new Error("Bluesky createRecord returned no uri or cid.");
  }

  return { uri: body.uri, cid: body.cid, url: postUrlFromUri(body.uri, session.handle) };
}

/**
 * Turn an AT URI into a browsable link.
 *
 * at://did:plc:abc/app.bsky.feed.post/3kabc -> https://bsky.app/profile/<handle or did>/post/3kabc
 * Returns the AT URI unchanged if it does not have the expected shape, rather
 * than producing a confidently wrong link.
 */
export function postUrlFromUri(uri: string, handle?: string): string {
  const match = /^at:\/\/([^/]+)\/app\.bsky\.feed\.post\/(.+)$/.exec(uri);
  if (!match) return uri;
  const [, did, rkey] = match;
  return `https://bsky.app/profile/${handle ?? did}/post/${rkey}`;
}

// ==========================================================================
// src/utils/telegramClient.ts
// ==========================================================================

/**
 * Telegram channel publishing, via the Bot API.
 *
 * The second lane that can go live without waiting on an app review, so it is
 * worth having early even though it is milestone 6 in the plan.
 *
 * Limits below are the Bot API's own, confirmed against its documentation, and
 * enforced before a request is sent:
 *
 *   photo        10 MB via multipart/form-data
 *   other files  50 MB (so video)
 *   caption      1024 characters
 *
 * Note that Telegram's photo limit is TEN times Bluesky's, so this lane can
 * carry the master render rather than the -web derivative.
 *
 * THE SETUP MISTAKE EVERYONE MAKES: the bot must be added to the channel as an
 * administrator with permission to post. Without that every call returns 403
 * and it reads exactly like a bad token. The error handler below says so
 * explicitly rather than passing Telegram's terse "Forbidden" through.
 */


export const TELEGRAM_API = "https://api.telegram.org";

/** 10 MB, for sendPhoto via multipart. */
export const MAX_PHOTO_BYTES = 10 * 1024 * 1024;
/** 50 MB, for every other file type via multipart. */
export const MAX_FILE_BYTES = 50 * 1024 * 1024;
/** Characters, not graphemes — the Bot API counts UTF-16 code units here. */
export const MAX_CAPTION_LENGTH = 1024;

export interface TelegramCredentials {
  botToken: string;
  /** "@channelusername" or a numeric id, which for a channel starts -100. */
  chatId: string;
}


export interface TelegramOptions {
  fetch?: Fetcher;
  api?: string;
}

/**
 * Read credentials from the environment.
 *
 * The token is never logged, never returned in an error message and never
 * placed in a URL that gets printed — which needs care here, because the Bot
 * API puts the token IN THE PATH. Every error message below is built from the
 * method name rather than from the request URL for exactly that reason.
 */
export function telegramCredentialsFromEnv(
  env: NodeJS.ProcessEnv = process.env,
): TelegramCredentials {
  const botToken = (env.TELEGRAM_BOT_TOKEN ?? "").trim();
  const chatId = (env.TELEGRAM_CHANNEL_CHAT_ID ?? "").trim();

  const missing: string[] = [];
  if (botToken === "") missing.push("TELEGRAM_BOT_TOKEN");
  if (chatId === "") missing.push("TELEGRAM_CHANNEL_CHAT_ID");
  if (missing.length > 0) {
    throw new Error(
      `Cannot publish to Telegram: missing environment variable(s): ${missing.join(", ")}. ` +
        `Trigger.dev variables are per-environment — set in Development is not set in Production.`,
    );
  }

  // Bot tokens are <numeric bot id>:<secret>. Checking the shape catches a
  // half-pasted value now rather than as a 404 later, and a 404 from this API
  // is indistinguishable from a wrong method name.
  if (!/^\d+:[A-Za-z0-9_-]{20,}$/.test(botToken)) {
    throw new Error(
      `TELEGRAM_BOT_TOKEN does not look like a bot token (expected <digits>:<secret>). ` +
        `Check it was pasted whole — a truncated token fails as a 404, which reads like a bug ` +
        `in the code rather than a bad credential.`,
    );
  }

  // A channel is either @username or a numeric id beginning -100. A bare
  // positive number is a private chat, not a channel, and posting to it would
  // succeed while reaching nobody — the worst kind of wrong.
  if (!/^@[A-Za-z][A-Za-z0-9_]{4,}$/.test(chatId) && !/^-100\d+$/.test(chatId)) {
    throw new Error(
      `TELEGRAM_CHANNEL_CHAT_ID "${chatId}" is not a channel identifier. Use either ` +
        `@yourchannel or the numeric id, which for a channel begins with -100. A plain ` +
        `positive number is a private chat: posting there would succeed and reach nobody.`,
    );
  }

  return { botToken, chatId };
}

export function validateCaption(caption: string): string[] {
  if (caption.length > MAX_CAPTION_LENGTH) {
    return [
      `caption is ${caption.length} characters, over Telegram's ${MAX_CAPTION_LENGTH} limit`,
    ];
  }
  return [];
}

export function validateMedia(bytes: Uint8Array, kind: "image" | "video"): string[] {
  const problems: string[] = [];
  const limit = kind === "image" ? MAX_PHOTO_BYTES : MAX_FILE_BYTES;
  if (bytes.byteLength === 0) problems.push("media is zero bytes");
  if (bytes.byteLength > limit) {
    problems.push(
      `${kind} is ${bytes.byteLength} bytes, over Telegram's ${limit}-byte limit for this type`,
    );
  }
  return problems;
}

/**
 * Turn a Bot API failure into something actionable.
 *
 * Deliberately never includes the request URL, because the token is in the
 * path. The method name is enough to locate the call.
 */
export function describeTelegramError(
  method: string,
  status: number,
  description: string,
): string {
  const base = `Telegram ${method} failed: HTTP ${status}${description ? ` — ${description}` : ""}`;

  if (status === 403) {
    return (
      `${base}. This almost always means the bot is not an ADMINISTRATOR of the channel, ` +
      `or lacks permission to post. Add it: channel > Administrators > Add Administrator > ` +
      `your bot, with "Post Messages" enabled. It reads like a bad token but it is not one.`
    );
  }
  if (status === 400 && /chat not found/i.test(description)) {
    return (
      `${base}. The chat id is wrong, or the bot has never been added to that channel. ` +
      `For a public channel use @username; for a private one use the numeric -100… id.`
    );
  }
  if (status === 401) {
    return `${base}. The bot token is rejected — check TELEGRAM_BOT_TOKEN is current and whole.`;
  }
  if (status === 429) {
    return `${base}. Rate limited. The scheduler paces posts, so this suggests something is retrying in a loop.`;
  }
  return base;
}

async function callBotApi(
  credentials: TelegramCredentials,
  method: string,
  form: FormData,
  options: TelegramOptions = {},
): Promise<Record<string, unknown>> {
  const fetcher = options.fetch ?? fetch;
  const api = options.api ?? TELEGRAM_API;

  const response = await fetcher(`${api}/bot${credentials.botToken}/${method}`, {
    method: "POST",
    body: form,
  });

  let payload: { ok?: boolean; description?: string; result?: Record<string, unknown> } = {};
  try {
    payload = (await response.json()) as typeof payload;
  } catch {
    /* fall through to the status-based message */
  }

  if (!response.ok || payload.ok !== true) {
    throw new Error(
      describeTelegramError(method, response.status, payload.description ?? ""),
    );
  }
  return payload.result ?? {};
}

export interface TelegramPostResult {
  messageId: number;
  /** Browsable link when the channel is public; empty for a private one. */
  url: string;
}

export function messageUrl(chatId: string, messageId: number): string {
  // Only a public @username channel has a t.me/<name>/<id> permalink. For a
  // numeric id there is no stable public URL, and inventing one would be worse
  // than returning nothing.
  if (chatId.startsWith("@")) return `https://t.me/${chatId.slice(1)}/${messageId}`;
  return "";
}

export interface TelegramPostRequest {
  bytes: Uint8Array;
  filename: string;
  mimeType: string;
  kind: "image" | "video";
  caption: string;
  /** The asset being published, for the last-moment safety check. */
  asset?: AssetRef;
}

/**
 * Post media to the channel.
 *
 * As with Bluesky, assertPublishAllowed runs here as well as at routing time.
 * Telegram is on the safe-only list, so an explicit render must be refused at
 * the last possible moment regardless of what queued it.
 */
export async function publishToTelegram(
  credentials: TelegramCredentials,
  request: TelegramPostRequest,
  options: TelegramOptions = {},
): Promise<TelegramPostResult> {
  if (request.asset) {
    assertPublishAllowed("telegram", request.asset);
  }

  const problems = [
    ...validateMedia(request.bytes, request.kind),
    ...validateCaption(request.caption),
  ];
  if (problems.length > 0) {
    throw new Error(`Refusing to publish to Telegram: ${problems.join("; ")}`);
  }

  const method = request.kind === "image" ? "sendPhoto" : "sendVideo";
  const field = request.kind === "image" ? "photo" : "video";

  const form = new FormData();
  form.append("chat_id", credentials.chatId);
  form.append("caption", request.caption);
  form.append(
    field,
    new Blob([Buffer.from(request.bytes)], { type: request.mimeType }),
    request.filename,
  );

  const result = await callBotApi(credentials, method, form, options);
  const messageId = Number(result.message_id);
  if (!Number.isFinite(messageId)) {
    throw new Error(`Telegram ${method} returned no message_id.`);
  }

  return { messageId, url: messageUrl(credentials.chatId, messageId) };
}

// ==========================================================================
// src/trigger/publishPipeline.ts
// ==========================================================================

/**
 * The pipeline: a finished render becomes scheduled posts.
 *
 *   publish-planner  (cron)  lists new assets, routes them, assigns slots,
 *                            and triggers one delayed child per destination
 *   publish-one      (child) wakes at its slot, re-checks the rail, publishes
 *
 * THERE IS NO QUEUE TABLE, on purpose. Trigger.dev's own `delay` and
 * `idempotencyKey` are the queue. That was verified by compiling against the
 * installed 3.3.17 SDK rather than assumed from the docs. It matters because a
 * queue I store myself is a queue I have to make crash-safe, and the platform
 * has already done that: a duplicate trigger with the same idempotency key is
 * refused server-side, so a planner that runs twice cannot double-post even if
 * my own logic is wrong.
 *
 * The planner is therefore safe to run as often as you like. Running it twice
 * is a no-op, not a second set of posts.
 */










/** Extension to media kind. An unknown extension is never guessed at. */
export function mediaKindFromKey(key: string): MediaKind | null {
  const lower = key.toLowerCase();
  if (/\.(jpe?g|png|webp)$/.test(lower)) return "image";
  if (/\.(mp4|mov|webm)$/.test(lower)) return "video";
  return null;
}

/** MIME type for the lanes that need one stated explicitly. */
export function mimeTypeFromKey(key: string): string | null {
  const lower = key.toLowerCase();
  if (/\.jpe?g$/.test(lower)) return "image/jpeg";
  if (/\.png$/.test(lower)) return "image/png";
  if (/\.webp$/.test(lower)) return "image/webp";
  if (/\.mp4$/.test(lower)) return "video/mp4";
  return null;
}

/** True for the downscaled derivative ComfyUI writes beside each master. */
export function isWebDerivative(key: string): boolean {
  return /-web\.[a-z0-9]+$/i.test(key);
}

/**
 * The `-web` sibling of a master key.
 *
 * "safe/2026-09-17/render-01.png" -> "safe/2026-09-17/render-01-web.jpg"
 *
 * The derivative is always JPEG, because that is what the ComfyUI workflow
 * writes and what keeps it under Bluesky's 1,000,000-byte ceiling.
 */
export function webDerivativeKey(masterKey: string): string {
  return masterKey.replace(/\.[a-z0-9]+$/i, "-web.jpg");
}

const HOT_BUCKET = () => requireEnv("TIGRIS_BUCKET_NAME");

/** Assets written in the last `hours`, excluding `-web` derivatives. */
export async function listRecentAssets(hours = 24): Promise<AssetRef[]> {
  const bucket = HOT_BUCKET();
  const cutoff = Date.now() - hours * 60 * 60 * 1000;
  const found: AssetRef[] = [];
  let token: string | undefined;

  do {
    const page = await tigrisClient.send(
      new ListObjectsV2Command({ Bucket: bucket, ContinuationToken: token }),
    );
    for (const item of page.Contents ?? []) {
      if (!item.Key || item.Key.endsWith("/")) continue;
      if (isWebDerivative(item.Key)) continue; // a derivative is not its own post
      if (!item.LastModified || item.LastModified.getTime() < cutoff) continue;

      const kind = mediaKindFromKey(item.Key);
      if (kind === null) {
        // Loudly, not silently: an unrecognised extension is a real thing to fix.
        logger.warn(
          `Skipping "${item.Key}": unrecognised extension, so its media kind cannot be ` +
            `determined. Nothing is guessed at here. Add the extension to mediaKindFromKey ` +
            `if this is a format we should publish.`,
        );
        continue;
      }
      found.push({ key: item.Key, kind });
    }
    token = page.NextContinuationToken;
  } while (token);

  return found.sort((a, b) => a.key.localeCompare(b.key));
}

async function bodyToBytes(body: unknown): Promise<Uint8Array> {
  const stream = body as { transformToByteArray?: () => Promise<Uint8Array> };
  if (typeof stream.transformToByteArray === "function") {
    return stream.transformToByteArray();
  }
  throw new Error("Unexpected S3 body type — cannot read the object.");
}

/**
 * Fetch the bytes a given platform should publish.
 *
 * For a size-constrained lane this prefers the `-web` derivative. If the
 * derivative is missing it falls back to the master and then fails the size
 * check with a message naming BOTH keys — because "image too large" without
 * saying which file and which derivative it wanted is a message that costs an
 * hour to act on.
 */
export async function fetchForPlatform(
  asset: AssetRef,
  platform: PlatformId,
): Promise<{ bytes: Uint8Array; mimeType: string; key: string }> {
  const bucket = HOT_BUCKET();
  const prefersDerivative = platform === "bluesky" && asset.kind === "image";

  const candidates = prefersDerivative
    ? [webDerivativeKey(asset.key), asset.key]
    : [asset.key];

  let lastError: unknown;
  for (const key of candidates) {
    try {
      const object = await tigrisClient.send(
        new GetObjectCommand({ Bucket: bucket, Key: key }),
      );
      const bytes = await bodyToBytes(object.Body);
      const mimeType = object.ContentType ?? mimeTypeFromKey(key) ?? "application/octet-stream";

      if (prefersDerivative && key === asset.key && bytes.byteLength > MAX_BLOB_BYTES) {
        throw new AbortTaskRunError(
          `No web derivative for "${asset.key}" and the master is ${bytes.byteLength} bytes, ` +
            `over Bluesky's ${MAX_BLOB_BYTES}-byte limit. Expected to find ` +
            `"${webDerivativeKey(asset.key)}". Have the ComfyUI workflow write the -web copy ` +
            `(1600px longest edge, JPEG q85) alongside the master.`,
        );
      }
      return { bytes, mimeType, key };
    } catch (error) {
      if (error instanceof AbortTaskRunError) throw error;
      lastError = error;
    }
  }
  throw new Error(
    `Could not read any of [${candidates.join(", ")}] from "${bucket}": ${String(lastError)}`,
  );
}

export interface PublishOnePayload {
  key: string;
  kind: MediaKind;
  platform: PlatformId;
  /**
   * Caption OVERRIDE. Omit it and one is generated for this platform.
   *
   * Supplying it explicitly is what makes a manual test run from the dashboard
   * console free and deterministic — no OpenAI call, no variation.
   */
  text?: string;
  altText?: string;
}

/**
 * Resolve the caption for a post.
 *
 * Generation failures THROW. A silent fall back to a placeholder would publish
 * "New image: render-01.jpg" for weeks before anyone noticed captions had
 * stopped being written — the same shape as a job that logs an error and
 * returns normally. Set CAPTIONS_ENABLED=false to opt out deliberately, which
 * is a different thing from failing.
 */
export async function resolveCaption(
  payload: PublishOnePayload,
  asset: AssetRef,
): Promise<string> {
  if (typeof payload.text === "string" && payload.text.trim() !== "") {
    return payload.text;
  }

  const context = {
    asset,
    platform: payload.platform,
    ...(process.env.PROMO_LINK_URL ? { linkUrl: process.env.PROMO_LINK_URL.trim() } : {}),
    ...(process.env.CAPTION_INTENSITY
      ? { intensity: process.env.CAPTION_INTENSITY.trim() as "soft" | "direct" | "hard" }
      : {}),
  };

  // Only the exact string "false" opts out, the same rule as every other flag
  // in this project, so a typo cannot silently disable caption generation.
  if ((process.env.CAPTIONS_ENABLED ?? "").trim().toLowerCase() === "false") {
    logger.info("Caption generation is disabled; using the plain fallback.");
    return fallbackCaption(context);
  }

  return generateCaption(context);
}

export const publishOne = task({
  id: "publish-one",
  // One attempt. A retry here re-enters run() from the top and would publish a
  // SECOND post — the same shape as the RunPod double-submission earlier in this
  // project, except the cost is a duplicate on a public feed. Trigger.dev's
  // idempotency key stops a duplicate TRIGGER; it does not stop a retry of an
  // attempt that already succeeded in posting before failing afterwards.
  retry: { maxAttempts: 1 },
  run: async (payload: PublishOnePayload) => {
    const asset: AssetRef = { key: payload.key, kind: payload.kind };

    // The rail, for the third and final time. Routing checked it, the adapter
    // checks it, and it is checked here before a single byte is read — because
    // this is the run that actually posts.
    assertPublishAllowed(payload.platform, asset);

    if (payload.platform !== "bluesky" && payload.platform !== "telegram") {
      throw new AbortTaskRunError(
        `No adapter is built for ${payload.platform} yet. Bluesky and Telegram are live; ` +
          `Instagram, Facebook, TikTok and YouTube are waiting on app review.`,
      );
    }

    const caption = await resolveCaption(payload, asset);
    const media = await fetchForPlatform(asset, payload.platform);
    logger.info("Publishing", {
      captionGenerated: payload.text === undefined,
      platform: payload.platform,
      assetKey: asset.key,
      bytesFrom: media.key,
      bytes: media.bytes.byteLength,
      usedWebDerivative: media.key !== asset.key,
    });

    if (payload.platform === "telegram") {
      // Telegram's photo ceiling is 10 MB against Bluesky's 1,000,000 bytes, so
      // this lane carries the master render and fetchForPlatform never reaches
      // for the -web derivative.
      const result = await publishToTelegram(telegramCredentialsFromEnv(), {
        bytes: media.bytes,
        filename: media.key.split("/").pop() ?? "render",
        mimeType: media.mimeType,
        kind: asset.kind,
        caption,
        asset,
      });
      logger.info(
        result.url
          ? `Published to Telegram: ${result.url}`
          : `Published to Telegram, message ${result.messageId} (private channel, no permalink)`,
        { messageId: result.messageId, url: result.url },
      );
      return { platform: payload.platform, messageId: result.messageId, url: result.url };
    }

    const session = await createSession(blueskyCredentialsFromEnv());
    const result = await publishPost(session, {
      text: caption,
      asset,
      langs: ["en"],
      ...(asset.kind === "image"
        ? {
            images: [
              {
                bytes: media.bytes,
                mimeType: media.mimeType,
                // Alt text is required by the lexicon. Falling back to the
                // caption is better than an empty string for a screen reader.
                alt: payload.altText ?? caption.slice(0, 280),
              },
            ],
          }
        : {}),
    });

    logger.info(`Published to Bluesky: ${result.url}`, { uri: result.uri, url: result.url });
    return { platform: payload.platform, uri: result.uri, url: result.url };
  },
});

/**
 * Move an asset into a classified location, without touching the storage console.
 *
 * Exists because getting a file under a prefix through a web console turned out
 * to be the single hardest step in this whole project for the person who has to
 * do it. Trigger.dev already holds the storage credentials, so a task can do it
 * with a button.
 *
 * IT NEVER CHOOSES THE CLASSIFICATION. The destination is supplied by a human
 * and must already be under safe/ or explicit/. Auto-filing a stray render into
 * safe/ would be exactly the unrecoverable mistake the routing rail exists to
 * prevent — a machine guessing that something is publishable.
 */
export const copyAsset = task({
  id: "copy-asset",
  retry: { maxAttempts: 1 },
  run: async (payload: { from: string; to: string; deleteOriginal?: boolean }) => {
    const bucket = HOT_BUCKET();
    const from = payload.from.replace(/^\/+/, "").trim();
    const to = payload.to.replace(/^\/+/, "").trim();

    if (from === "" || to === "") {
      throw new AbortTaskRunError("Both `from` and `to` are required.");
    }
    if (from === to) {
      throw new AbortTaskRunError("`from` and `to` are the same key — nothing to do.");
    }

    // The whole point of the guard: a destination nobody classified is not a
    // destination. Refusing here keeps the invariant that everything in a
    // publishable location was put there deliberately.
    const contentClass = classifyFromKey(to);
    if (contentClass === null) {
      throw new AbortTaskRunError(
        `Refusing to copy to "${to}": it is not under "safe/" or "explicit/". ` +
          `Choose the classification yourself — this task will not guess it for you, ` +
          `because guessing wrong is how explicit content reaches a public platform.`,
      );
    }

    const source = await tigrisClient.send(
      new HeadObjectCommand({ Bucket: bucket, Key: from }),
    );

    await tigrisClient.send(
      new CopyObjectCommand({
        Bucket: bucket,
        // CopySource is bucket + key, and the key must be URI-encoded or any
        // space or unusual character in the filename silently 404s.
        CopySource: `${bucket}/${encodeURIComponent(from)}`,
        Key: to,
      }),
    );

    // Verify it actually landed and is the same size. A copy that "succeeded"
    // and produced a zero-byte object would otherwise be reported as done.
    const copied = await tigrisClient.send(
      new HeadObjectCommand({ Bucket: bucket, Key: to }),
    );
    if (copied.ContentLength !== source.ContentLength) {
      throw new Error(
        `Copy verification failed: "${from}" is ${source.ContentLength} bytes but ` +
          `"${to}" is ${copied.ContentLength}. The original has NOT been deleted.`,
      );
    }

    let deleted = false;
    if (payload.deleteOriginal === true) {
      // Only after the copy is verified. A failed copy must never lose the file.
      await tigrisClient.send(new DeleteObjectCommand({ Bucket: bucket, Key: from }));
      deleted = true;
    }

    logger.info(`Copied ${from} -> ${to}`, {
      bytes: copied.ContentLength,
      contentClass,
      originalDeleted: deleted,
    });

    return {
      from,
      to,
      bytes: copied.ContentLength ?? 0,
      contentClass,
      originalDeleted: deleted,
    };
  },
});

export interface PlannerResult {
  assetsSeen: number;
  triggered: number;
  deferred: number;
  blocked: number;
}

export const publishPlanner = schedules.task({
  id: "publish-planner",
  // Hourly. Safe to run more often — a duplicate trigger is refused by the
  // idempotency key, so a second pass in the same hour is a no-op.
  cron: { pattern: "0 * * * *", timezone: "UTC" },
  run: async (): Promise<PlannerResult> => {
    const assets = await listRecentAssets(24);
    logger.info(`Planner found ${assets.length} candidate asset(s) in the last 24h`, {
      keys: assets.map((a) => a.key),
    });

    const inputs: PlanInput[] = [];
    let blocked = 0;

    for (const asset of assets) {
      const decision = routeAsset(asset);
      if (decision.blockedReason) {
        // Never silent. An unclassified asset is a thing somebody must fix.
        logger.error(`BLOCKED: ${asset.key}`, { reason: decision.blockedReason });
        blocked += 1;
        continue;
      }
      if (decision.destinations.length === 0) {
        logger.warn(`No destination for ${asset.key}`, {
          rejected: decision.rejected.map((r) => `${r.platform}: ${r.reason}`),
        });
        continue;
      }
      inputs.push({ asset, destinations: decision.destinations });
    }

    const plan = planSchedule(inputs, new Date(), [], DEFAULT_SCHEDULE);

    let triggered = 0;
    for (const post of plan.scheduled) {
      // Only lanes with a working adapter are dispatched. The rest are planned
      // and reported so the schedule is visible before the adapters exist.
      if (post.platform !== "bluesky" && post.platform !== "telegram") {
        logger.info(`Planned (no adapter yet): ${post.platform} ${post.asset.key}`, {
          scheduledFor: post.scheduledFor.toISOString(),
        });
        continue;
      }

      await publishOne.trigger(
        {
          key: post.asset.key,
          kind: post.asset.kind,
          platform: post.platform,
          // No text: publish-one generates a per-platform caption at its slot.
          // Generating here would produce one caption reused across every
          // destination, which is the cross-posting fingerprint the staggered
          // scheduling exists to avoid.
        },
        {
          delay: post.scheduledFor,
          // Server-side duplicate protection. This is what makes the planner
          // safe to re-run: the same asset and platform can only ever produce
          // one queued post, regardless of how many times this task runs.
          idempotencyKey: post.idempotencyKey,
        },
      );
      triggered += 1;
      logger.info(`Queued ${post.platform} ${post.asset.key}`, {
        scheduledFor: post.scheduledFor.toISOString(),
        idempotencyKey: post.idempotencyKey,
      });
    }

    for (const item of plan.deferred) {
      logger.info(`Deferred ${item.platform} ${item.asset.key}`, { reason: item.reason });
    }

    const result: PlannerResult = {
      assetsSeen: assets.length,
      triggered,
      deferred: plan.deferred.length,
      blocked,
    };

    if (blocked > 0) {
      // A blocked asset means a render is sitting in storage that will never be
      // published. The run stays green for the posts that worked, but this must
      // not be discoverable only by reading logs nobody opens.
      throw new Error(
        `${blocked} asset(s) could not be classified and were not published. ` +
          `See the BLOCKED lines above — each one names the key. Move them under safe/ or ` +
          `explicit/ and they will be picked up on the next pass.`,
      );
    }

    return result;
  },
});
